version: '3.8'

services:
  # --- BASE DE DONNÉES (Source Marketing & Airflow) ---
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- STOCKAGE OBJET (Data Lakehouse S3) ---
  minio:
    image: minio/minio
    ports:
      - "9000:9000" # API S3
      - "9001:9001" # Console Web
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data

  # --- ORCHESTRATEUR (Airflow Webserver) ---
  airflow-webserver:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      # AJOUT DE PYTEST ET PYTEST-COV ICI
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas beautifulsoup4 requests sqlalchemy psycopg2-binary pytest pytest-cov
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./tests:/opt/airflow/tests  # <--- LE PONT POUR TES TESTS
    command: webserver

  # --- PLANIFICATEUR (Airflow Scheduler) ---
  airflow-scheduler:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - _PIP_ADDITIONAL_REQUIREMENTS=pandas beautifulsoup4 requests sqlalchemy psycopg2-binary pytest pytest-cov
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./scripts:/opt/airflow/scripts
      - ./tests:/opt/airflow/tests  # <--- LE PONT POUR TES TESTS
    command: scheduler

volumes:
  postgres_data:
